### ISSUE TITLE
"Base" Scene Files for Post-Processing

### ISSUE THREAD

**Issue by AidanWUSTL** [KEGarciaLab/aMSM_AD#16]
Hello Sammy,

I'm working on setting up these scripts/files into a docker image for our use with reproducing some results and eventually moving to new data. If possible, could the scene files used within the "ADNIPostProcessing.sh" script be uploaded to the repository, or otherwise another platform to share?

I know there are a handful which are utilized, such as "base.scene," so whichever ones are still relevant to the pipeline would be great to access. Happy to talk over some of this if desired!

Best,
Aidan

**Comment by SammyRigdon** [comment]
@AidanWUSTL The scenes have been added. For reference on the naming conventions, the images generated will have a base image and a "no-scale" image. The no-scale images are generated with a specific and consistent range on the maps so colors are consistent. Any reverse registrations will additionally have a series of "inverted" images. These are simply inverting the map so it matches the forward registration as a way to help eliminate noise. Closing issue now.

**Comment by AidanWUSTL** [comment]
Thanks so much for this, Sammy! I appreciate the quick upload, this should help me finish off some of our implementation!
